name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: npm install
      - name: Test
        run: npm run "./node_modules/.bin/wdio ./wdio.conf.js"
      - name: Upload Logs
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: log/